"""Conformance vectors for :mod:`spirrow_mindwire.identity.normalize` (ADR-2026-05-29-11).

``tests/fixtures/adr11_normalize_vectors.json`` is the canonical copy of the ADR-11
normalisation vectors. spirrow-magickit carries a byte-identical port of this file
(``tests/fixtures/adr11_normalize_vectors.json`` plus a ``.provenance.json`` that pins
``source_commit`` and ``sha256_lf_text``) and runs its own port of the rule over it.
This test is the mindwire side of that contract: the canonical implementation must
satisfy the canonical vectors.

The vectors were generated by running this repo's ``normalize.py`` (blob ``57c43cb``,
unchanged since ``10aabb9``) over the inputs, so this test adds no new behaviour — it
only pins what the rule already does, so that a change to the rule shows up here as a
red test instead of silently diverging from the magickit port.

The hash pin (``sha256`` of the LF-normalised text, the same key magickit's provenance
file uses) means the fixture cannot be edited without this test noticing: editing the
vectors is a cross-repo change and must be made on both sides together.

Spec: spirrow-magickit chatroom ``T-magickit-stop-disposition-intake`` DESIGN v11 §3 /
v12 §2.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import pytest

from spirrow_mindwire.identity import find_collisions, normalize_identity_key

_FIXTURE = Path(__file__).parent / "fixtures" / "adr11_normalize_vectors.json"

# sha256 of the fixture's text with CRLF normalised to LF (v10 rule; identical to the
# ``sha256_lf_text`` value in spirrow-magickit's provenance file).
_SHA256_LF_TEXT = "450595dd2129bef0eec592bf81137343fea96556def77a95d2e9f837beac60d0"


def _load() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(_FIXTURE.read_text(encoding="utf-8"))
    return data


def test_fixture_hash_matches_the_pinned_value() -> None:
    text = _FIXTURE.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert hashlib.sha256(text.encode("utf-8")).hexdigest() == _SHA256_LF_TEXT


def test_fixture_is_not_empty() -> None:
    data = _load()
    assert data["normalize"], "normalize vectors must not be empty"
    assert data["collisions"], "collision vectors must not be empty"


@pytest.mark.parametrize(
    ("raw", "expected"),
    [tuple(pair) for pair in _load()["normalize"]],
)
def test_normalize_vector(raw: str, expected: str) -> None:
    assert normalize_identity_key(raw) == expected


@pytest.mark.parametrize(
    "case",
    _load()["collisions"],
    ids=lambda case: repr(case["input"]),
)
def test_collision_vector(case: dict[str, Any]) -> None:
    assert find_collisions(case["input"]) == case["expected"]
